### ISSUE TITLE
SyntaxError: Unexpected token '.' 

### ISSUE THREAD

**Issue by aheckmann** [sortxyz/react-components#4]
Our react components use [react-data-grid which uses the JavaScript optional chaining feature](https://github.com/adazzle/react-data-grid/issues/2928) which [doesn't work in older versions of Chrome](https://caniuse.com/mdn-javascript_operators_optional_chaining) (normally the most up to date browser). [Here's a post about it](https://blog.jim-nielsen.com/2022/a-web-for-all/). 

browser Chrome Mobile 78.0.3904
browser.name Chrome Mobile
device HD1900
device.family HD1900
os Android 10
os.name Android

**Comment by anthonypecchillo** [comment]
Resolved by: https://github.com/sortxyz/react-components/pull/29
